---
title: "Ambrosia"
uniqueid: ambrosia
---

## Ingredientes

* 1 litro de leite integral;
* 350 g (2 xícaras) de açúcar cristal;
* 6 ovos de galinha (clara e gema);
* 1 limão pequeno;
* Especiarias a gosto (canela em pau, cravo da índia, anis estrelado, baunilha, raspas de casca de limão)

## Modo de preparo

Coloque aproximadamente 100 g de açúcar em uma panela, preferencialmente de fundo grosso. Com fogo baixo,
derreta o açúcar e mantenha sob fervura branda até obter coloração dourada.

Acrescente o leite, preferencialmente já aquecido, à calda de açúcar caramelizado. Caso a calda de açúcar
caramelizado endureça, mantenha a mistura sob fervura moderada até que o açúcar seja completamente dissolvido
pelo leite.

Acrescente o restante do açúcar e os ovos, preferencialmente já batidos, mexendo a mistura para garantir sua
homogeneização.

Adicione especiarias a gosto -- as especiarias mais comuns são a canela em pau (1 ou 2 unidade) e o cravo da 
Índia (4 a 8 unidades) --, e ferva a mistura por um ou dois minutos.

Finalmente, adicione o suco de limão e mexa a mistura para garantir sua homogeneização. O suco de limão é 
responsável pela coagulação do leite. A partir da sua adição, terá inicio a formação dos grumos característicos
da ambrosia.

Mantenha fervura branda para evaporar o excesso de líquido da mistura. Mexa de vez em quando para evitar que 
os grumos grudem-se às paredes da panela ou que formem uma massa única. O tamanho final dos grumos depende da
frequência e intensidade de meximento da mistura.

Remova do fogo assim que a quantidade de líquido restante for a desejada. Aguarde a temperatura baixar antes 
de servir -- para não queimar a língua. Se desejar, adicione as especiarias da sua preferência.

## Observações

* Essa receita rende, aproximadamente, seis porções.

* O tempo de preparo é de, aproximadamente, uma hora.

## Referências

http://www.tudogostoso.com.br/receita/37486-ambrosia-facil.html

http://pt.wikihow.com/Caramelizar-A%C3%A7%C3%BAcar

https://pt.wikipedia.org/wiki/Ambrosia
