---
title: "Projetos"
uniqueid: content
---

Praticamente todos os projetos em que estou envolvido têm alguma relação com a *pedologia quantitativa*. 
Assim sendo, acabo tendo grandes dificuldades em classificá-los como pertencendo à essa ou àquela área do 
conhecimento. As coisas ficam mais fáceis quando penso na *pedologia quantitativa* como o tema gerador dos 
projetos em que estou envolvido. Por exemplo, algumas vezes desenvolvo ferramentas computacionais sem qualquer 
relação com a *pedologia quantitativa*. Contudo, a razão de seu desenvolvimento foi exatamente a de dar um
pequeno passo na caminhada rumo a resolução de um problema maior cuja origem é a *pedologia quantitativa*.

## Ensino de Pedologia Quantitativa

* Projetos ativos/prioritários:
    1. Pedologia Quantitativa feita Simples. Acesse a versão preliminar do livro 
       [aqui](http://samuel-rosa.github.io/pedologia-quantitativa/_book/).

* Projetos inativos/não-prioritários:
    1. Newsletter da Comissão de Pedometria da Sociedade Brasileira de Ciência do Solo. Acesse as versões
       publicadas da Newsletter [aqui](https://github.com/samuel-rosa/pedometria).

## Software para Escrita Científica

* Projetos ativos/prioritários:
    1. Classe LaTeX `UFRuralRJ` para formatação de documentos acadêmicos da Universidade Federal Rural do Rio 
       de Janeiro. Acesse o código fonte [aqui](https://github.com/samuel-rosa/UFRuralRJ) e o manual de uso 
       [aqui](http://samuel-rosa.github.io/UFRuralRJ/_book/).

* Projetos inativos/não-prioritários:
    1. Arquivos de estilo `jstyle` para formatação automática de referências bibliográficas usando JabRef e
       LibreOffice. Acesse o código fonte [aqui](https://github.com/samuel-rosa/RefBib).
    2. Pacote LaTeX `pedometrianews` para formatação da Newsletter da Comissão de Pedometria da Sociedade 
       Brasileira de Ciência do Solo. Acesse o código fonte [aqui](https://github.com/samuel-rosa/pedometrianews)
       e as versões publicadas da Newsletter [aqui](https://github.com/samuel-rosa/pedometria).

## Software para Pedologia Quantitativa

* Projetos ativos/prioritários:
    1. Pacote `pedometrics` para o `R` contendo ferramentas e técnicas para *pedologia quantitativa*. 
       Acesse o código fonte [aqui](https://github.com/samuel-rosa/pedometrics) ou baixe a última versão
       publicada [daqui](https://cran.r-project.org/web/packages/pedometrics/).
    2. Pacote `spsann` para o `R` contendo ferramentas para otimização de configurações amostrais usando 
       recozimento simulado. Acesse o código fonte [aqui](https://github.com/samuel-rosa/spsann) ou baixe a
       última versão publicada [daqui](https://cran.r-project.org/web/packages/spsann/).
