---
title: "Contato"
uniqueid: contact
---

Você pode entrar em contato comigo de diversas maneiras.

A primeira delas é postando um comentário público no final de cada página. Essa modalidade é recomendada caso
você queira fazer algum comentário sobre as ideias que publiquei aqui.

Destaco, contudo, que todos os comentários públicos são moderados, e que as opiniões neles expressas são de
responsabilidade exclusiva dos seus 
autores. Peço que não sejam adicionados links externos aos comentários, e que o texto seja curto, não 
ultrapassando 1000 caracteres. Comentários com ofensas pessoais serão eliminados imediatamente. Não há, 
contudo, moderação ideológica. A ideia dos comentários é promover o debate a cerca das ideias aqui 
publicadas.

A segunda forma de entrar em contato comigo, talvez a **mais eficiente**, é enviando uma mensagem para
<font color="blue"><u>alessandrosamuelrosa</u></font> no <font color="blue"><u>gmail.com</u></font>.

Você pode me enviar uma mensagem de e-mail caso queira fazer algum comentário privado sobre as ideias que
publiquei aqui ou em outro lugar (ou mesmo para discutir suas próprias ideias).

Você também pode me enviar uma mensagem de e-mail caso esteja interessado em agendar uma visita minha à sua
instituição ou empresa para uma palestra ou curso de curta duração. Mas atenção: o contato para agendamento 
de **palestras** ou **cursos** de curta duração requer, no mínimo, **seis meses de antecedência**.

Uma terceira forma de entrar em contato comigo é via 
[ResearchGate](https://www.researchgate.net/profile/Alessandro_Samuel-Rosa). Ali você pode, além de enviar-me
uma mensagem, dar uma olhada nos trabalhos que publiquei, bem como fazer comentários ou questionamentos sobre
os mesmos.
