---
title: "Apresentação"
uniqueid: index
---

Seja bem vindo ao *website* que construí para compartilhar minhas experiências e conhecimentos com 
estudantes, professores, pesquisadores e profissionais da Ciência do Solo dos países de língua portuguesa, 
sobretudo o Brasil. Os tópicos que discuto pertencem à área da pedologia quantitativa, também conhecida como
pedometria.

Meu foco no Brasil se deve ao fato de que a popularização do uso de métodos matemáticos e estatísticos para
o estudo da distribuição e gênese do solo é bastante recente no país. O número de pesquisadores brasileiros
atuando nessa área também é pequeno se comparado às condições europeias e norte-americanas. Poucos são os 
programas de pós-graduação brasileiros que possuem em seu corpo docente pesquisadores dedicados à pedologia 
quantitativa. Raros são os periódicos científicos brasileiros com editores especialistas na área. Ao mesmo 
tempo, cresce a necessidade por profissionais devidamente capacitados para o uso de métodos matemáticos e 
estatísticos para a modelagem quantitativa do solo. Além de ajudar a avançar a pesquisa em pedologia 
quantitativa, meu objetivo com este *website* é contribuir para a formação de tais profissionais.

Destaco que os conhecimentos que aqui compartilho não pretendem esgotar quaisquer discussões a cerca da
modelagem quantitativa do solo. Pelo contrário, eles constituem uma simples introdução ou suplemento a 
trabalhos publicados, muitos deles há mais de décadas. Muito daquilo que apresento é composto por minhas 
reflexões e interpretações a cerca de tais trabalhos. Isso significa que o leitor é expressamente encorajado 
a sempre procurar pelos materiais originais de onde quaisquer informações tenham sido obtidas, evitando citar 
este *website* como referência bibliográfica principal em seus trabalhos. Em outras palavras, este 
*website* não foi criado com o objetivo de constituir uma fonte de conhecimento final, mas sim uma ponte 
entre aqueles que buscam conhecimento a cerca da pedologia quantitativa e aquilo que foi construído ao longo 
dos anos passados. Espero que esse objetivo seja alcançado e, assim, este *website* contribua para o 
avanço qualitativo da prática científica nesta área da ciência do solo.

## Como citar

Repito que o leitor é expressamente encorajado a sempre procurar pelos trabalhos originais de onde 
quaisquer informações aqui apresentadas tenham sido obtidas, evitando citar este *website* como
referência bibliográfica principal em seus trabalhos. Caso seja de interesse citar este *website*, 
recomendo que seja usado o seguinte formato:

> Samuel-Rosa, A. <em>Pedologia Quantitativa feita Simples</em>.
> Em: http://samuel-rosa.github.io. Acesso em: 01 Abril 1941.

Caso seja de interesse citar os comentários, interpretações e ideias pessoais que apresento em artigos 
específicos, basta usar o formato acima com o nome do artigo, a data de acesso e o respectivo endereço 
eletrônico.
