---
title: "Sobre mim"
uniqueid: myself
---

Eu nasci em uma pequena cidade do norte do Rio Grande do Sul (RS) chamada Espumoso. Ali eu vivi com minha
família em uma pequena propriedade rural até os 14 anos de idade, tendo completado toda minha formação básica 
na Escola Estadual de Ensino Fundamental José Clemente Pereira.

![Minha primeira foto acadêmica, na biblioteca da Escola José Clemente Pereira, em
1992.](images/futuro_pesquisador.jpg)

Em 2000 eu ingressei na Escola Agrotécnica Federal de Sertão (EAFS), RS, onde cursei o ensino médio. Ali
também obtive o título de Técnico Agrícola com Habilitação em Agropecuária, com estágio de pouco mais de um 
ano em uma fazenda de produção de hortaliças na ilha de Maui, Hawai’i, EUA. Foi durante meu período na EAFS 
que o interesse pelo movimento estudantil teve início. Destaco aqui o apoio dos professores Heitor José Cervo, 
Maria Alice Vernes Miglioranza, Roberto Zanatta Guerra, e Walter Lucca. Foi o convívio com esses professores
que fez nascer em mim a vontade de seguir a carreira docente. Quanto ao estágio nos EUA, organizado pela
International Farmers Aid Association (IFAA), além da formação técnica, foi fundamental para consolidar meu 
conhecimento da língua inglesa.

Aos 18 anos de idade ingressei no curso de Agronomia da Universidade Federal de Santa Maria (UFSM), RS, 
onde atuei no movimento estudantil (Federação dos Estudantes de Agronomia do Brasil, FEAB) e na iniciação 
científica (Departamento de Solos, DS-UFSM). Apesar da íntima ligação com a área de produção de hortaliças, 
atuei junto ao Setor de Pedologia, coordenado por 
[Ricardo Simão Diniz Dalmolin](http://lattes.cnpq.br/3735884911693854), durante os cinco anos de 
iniciação científica. O apoio financeiro do Conselho Nacional de Desenvolvimento Científico e Tecnológico 
(CNPq), na forma de bolsa de iniciação científica, foi fundamental para que pudesse me dedicar ao estudo da
Pedologia. Durante a iniciação científica tive a oportunidade de trabalhar com diversos pesquisadores, 
principalmente [Fabrício de Araújo Pedron](http://lattes.cnpq.br/6868334304493274), do DS-UFSM, e 
[Deborah Pinheiro Dick](http://lattes.cnpq.br/1726585605611731), do Instituto de Química da
Universidade Federal do Rio Grande do Sul (UFRGS), Porto Alegre, RS. Ao final da graduação, ansioso em conhecer
outras universidades e realidades, mudei-me temporariamente para Seropédica, no Estado do Rio de Janeiro, para
realizar meu estágio de conclusão de curso na Universidade Federal Rural do Rio de Janeiro (UFRRJ) sob 
orientação de [Lúcia Helena Cunha dos Anjos](http://lattes.cnpq.br/7882538227876962) e 
[Marcos Gervásio Pereira](http://lattes.cnpq.br/3657759682534978). Na UFRRJ tive a feliz oportunidade de
participar de projetos de pesquisa desenvolvidos em parceria com diversas universidades e instituições de 
pesquisa, principalmente a Embrapa Solos. O longo (2004--2009) e prazeroso convívio com professores e
pesquisadores da UFSM, UFRGS e UFRRJ, reforçou ainda mais minha antiga vontade de seguir a carreira docente,
mas agora almejando também a carreira científica. Mas fora 
[Alexandre ten Caten](http://lattes.cnpq.br/4065267714747712), hoje professor da Universidade
Federal de Santa Catarina, o responsável por introduzir-me ao mundo da Pedometria, mais especificamente o
mapeamento digital do solo, tópico que acabou definindo os rumos de minha dissertação de mestrado e 
praticamente toda a minha atividade acadêmico-científica subsequente.

Seguindo o caminho acadêmico-científico, em 2010, iniciei o curso de mestrado do Programa de Pós-graduação em
Ciência do Solo (PPGCS) da UFSM, também sob a orientação de 
[Ricardo Simão Diniz Dalmolin](http://lattes.cnpq.br/3735884911693854) e o importantíssimo
financiamento do CNPq na forma de bolsa de mestrado. Durante esse período desenvolvi atividades nas áreas de
taxonomia, qualidade do solo, ensino de pedologia, mapeamento do solo e, principalmente, pedologia quantitiva 
ou pedometria. Meus principais e fundamentais colaboradores de campo e laboratório foram 
[Pablo Miguel](http://lattes.cnpq.br/4145554276881172), hoje professor da Universidade Federal de Pelotas 
(UFPel), [Jean Michel Moura-Bueno](http://lattes.cnpq.br/6826707506303568), hoje doutorando do PPGCS-UFSM, 
e [Andrisa Balbinot](http://lattes.cnpq.br/9480404753456469), hoje doutoranda do Programa de Pós-Graduação em
Fitossanidade da UFPel. Almejando uma formação docente mais ampla, durante o período do curso de mestrado 
também obtive o título de Licenciado para o Ensino Médio pelo Programa de Formação de Professores para a 
Educação Profissional da UFSM, seguindo os passos de colegas exemplares do PPGCS-UFSM, dentre eles 
[Alexandre ten Caten](http://lattes.cnpq.br/4065267714747712) e 
[Carlos Alberto Casali](http://lattes.cnpq.br/2314731193684558). O último, hoje professor da Universidade
Tecnológica Federal do Paraná, Campus Dois Vizinhos, PR, ainda orientou-me no estágio de docência no Instituto
Federal de Educação, Ciência e Tecnologia Farroupilha, Campus Julio de Castilhos, RS.

Era fevereiro de 2012 quando mudei-me para Seropédica, RJ, para cursar o doutorado no Curso de Pós-Graduação 
em Agronomia--Ciência do Solo (CPGA-CS) da UFRRJ com financiamento via bolsa de doutorado do CNPq. Minha
orientadora foi [Lúcia Helena Cunha dos Anjos](http://lattes.cnpq.br/7882538227876962), a quem eu já havia
"escolhido" para orientar-me no doutorado durante o estágio de conclusão do curso de graduação realizado na 
UFRRJ em 2009. Determinado a desenvolver meu projeto de doutorado em parceria com a Embrapa Solos, "escolhi", 
como co-orientador, [Gustavo de Mattos Vasques](http://lattes.cnpq.br/1838153897546051), um dos mais jovens
pesquisadores da Embrapa Solos, com doutorado em Pedometria recém concluído na University of Florida. Para
completar o time, [Gerard Heuvelink](http://www.isric.org/user/31), do ISRIC -- World Soil Information, 
Holanda, foi "escolhido" como segundo co-orientador, firmando assim meu direto interesse pela Pedometria. 
Graças ao financiamento do CNPq via programa Ciência sem Fronteiras, em 2014, tive a oportunidade de atuar como
pesquisador visitante no ISRIC desenvolvendo parte de meu projeto de doutoramento, bem como projetos do próprio
ISRIC. Lá tive a oportunidade de trabalhar diretamente com os pesquisadores 
[Bas Kempen](http://www.isric.org/user/26), [Hannes Reuter](https://www.researchgate.net/profile/Hannes_Reuter),
[Niels Batjes](http://www.isric.org/user/9), [Tom Hengl](http://www.isric.org/tomhengl), e
[Dick Brus](https://www.researchgate.net/profile/Dick_Brus), e com os programadores 
[Jorge Mendes de Jesus](https://www.researchgate.net/profile/Jorge_Mendes_De_Jesus) e 
[Eloi Ribeiro](http://www.isric.org/user/34). Ao final de quatro difíceis mas prazerosos anos de trabalho, 
meu projeto de doutoramento contribuiu para o entendimento de algumas das fontes de incerteza na modelagem
espacial do solo usando modelos estatísticos, mais especificamente os dados usados para a calibração de tais
modelos.

Logo após o doutorado, em março de 2016, iniciei minhas atividades como pesquisador visitante na UFRRJ, via
bolsa de pós-doutorado da Coordenação de Aperfeiçoamento de Pessoal de Nível Superior (CAPES), trabalhando sob
a supervisão de [Marcos Bacis Ceddia](http://lattes.cnpq.br/2115137917689655), em projeto de modelagem espacial
do solo na Amazônia. Terminado o projeto na UFRRJ, em dezembro de 2016, voltei a trabalhar na UFSM, novamente 
sob a supervisão de [Ricardo Simão Diniz Dalmolin](http://lattes.cnpq.br/3735884911693854), mas agora sob a 
forma de estágio pós-doutoral com bolsa da CAPES, cargo que ocupo até o presente momento. O projeto que 
desenvolvo na UFSM visa construir um repositório de dados de ferro do solo com cobertura nacional.
